### ISSUE TITLE
wordpress-compiler issues

### ISSUE THREAD

**Issue by davidak** [getnikola/plugins#136]
i have my wordpress blog since 2005, articles mostly written in plain HTML and tested a lot of plugins, using tags long before wp provided them etc... so this is really a stress test.

i also tried importing as Markdown: https://github.com/getnikola/plugins/issues/137

cc @felixfontein 

```
$ nikola import_wordpress --transform-to-html --install-wordpress-compiler davidakweblog.wordpress.2016-02-23.xml
[2016-02-23T09:18:33Z] INFO: compile_wordpress: Registered WordPress plugin wordpress_shortcode_gallery
[2016-02-23T09:18:33Z] INFO: compile_wordpress: Registered WordPress plugin wordpress_shortcode_code
[2016-02-23T09:18:33Z] INFO: compile_wordpress: Registered 2 WordPress plugins
[2016-02-23T09:18:34Z] INFO: init: Created empty site at new_site.
[2016-02-23T09:18:34Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/dashboard.jpg => new_site/files/blog/wp-content/uploads/2007/05/dashboard.jpg
[2016-02-23T09:18:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:35Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/screenshot7.jpeg => new_site/files/blog/wp-content/uploads/2007/05/screenshot7.jpeg
[2016-02-23T09:18:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:35Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012766.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012766.JPG
[2016-02-23T09:18:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:36Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:36Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012763.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012763.JPG
[2016-02-23T09:18:36Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:36Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:37Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png
[2016-02-23T09:18:37Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:37Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:37Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png
[2016-02-23T09:18:37Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:38Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:38Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png
[2016-02-23T09:18:38Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:38Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:39Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png
[2016-02-23T09:18:39Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:18:39Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "Google " because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "Startseite" because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "Blog" because it seems to contain no content.
[2016-02-23T09:18:39Z] WARNING: import_wordpress: Not going to import "Impressum" because it seems to contain no content.
[2016-02-23T09:18:42Z] ERROR: import_wordpress: Cannot interpret post "posts/435-text-zu-ascii-art" (language ) with post format wp!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugin_categories.py", line 124, in execute
    return self._execute(options, args)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 332, in _execute
    self.import_posts(channel)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 1015, in import_posts
    self.process_item_if_post_or_page(item)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 1005, in process_item_if_post_or_page
    self.write_attachments_info(destination, attachments)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 985, in write_attachments_info
    file.write(json.dumps(attachments).encode('utf-8'))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'300' is not JSON serializable
```

source of the article from wordpress:
```
<pre>
  _____ _______  _______   ____       _    ____   ____ ___ ___ 
 |_   _| ____\ \/ /_   _| |___ \     / \  / ___| / ___|_ _|_ _|
   | | |  _|  \  /  | |     __) |   / _ \ \___ \| |    | | | | 
   | | | |___ /  \  | |    / __/   / ___ \ ___) | |___ | | | | 
   |_| |_____/_/\_\ |_|   |_____| /_/   \_\____/ \____|___|___|
                                                               
</pre>

<!--more-->

So etwas kann man in stundenlanger Handarbeit basteln, aber einfacher geht es mit einem Generator.

Zu beachten ist dabei, dass man bei HTML den <code><pre> ... </pre></code> Tag braucht, da sonst immer nur ein Leerzeichen akzeptiert wird.

Und das sieht dann ziemlich scheisse aus!

Den Generator, um so etwas zu machen, findest du auf folgender Seite:

<a href="http://ascii.mastervb.net/" target="_blank">ascii.mastervb.net</a>

Hier gibt es noch ein paar mehr Schriftarten:

<a href="http://patorjk.com/software/taag/" target="_blank">patorjk.com/software/taag</a>

Auf der Seite kann man auch Bilder in ASCII umwandeln lassen, das hab ich aber nicht getestet und da gibt es auch tausende andere Seiten.

Viel Spass damit!
```

**Comment by felixfontein** [comment]
The problem here is not the WordPress compiler, but the WordPress importer (which is part of Nikola core). There's a problem with the image metadata export; the real problem is somewhere in this function: https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/import_wordpress.py#L462

**Comment by davidak** [comment]
i found the cause of this: https://github.com/getnikola/nikola/issues/2263

**Comment by felixfontein** [comment]
Cool! Thanks for investigating :)
