### ISSUE TITLE
import_wordpress issue

### ISSUE THREAD

**Issue by davidak** [getnikola/plugins#137]
i have my wordpress blog since 2005, articles mostly written in plain HTML and tested a lot of plugins, using tags long before wp provided them etc... so this is really a stress test.

i also tried importing as HTML: https://github.com/getnikola/plugins/issues/136

```
$ nikola import_wordpress davidakweblog.wordpress.2016-02-23.xml
[2016-02-23T09:53:50Z] INFO: init: Created empty site at new_site.
[2016-02-23T09:53:50Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/dashboard.jpg => new_site/files/blog/wp-content/uploads/2007/05/dashboard.jpg
[2016-02-23T09:53:50Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:50Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:51Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/05/screenshot7.jpeg => new_site/files/blog/wp-content/uploads/2007/05/screenshot7.jpeg
[2016-02-23T09:53:51Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:51Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:52Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012766.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012766.JPG
[2016-02-23T09:53:52Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:52Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:53Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2007/07/p1012763.JPG => new_site/files/blog/wp-content/uploads/2007/07/p1012763.JPG
[2016-02-23T09:53:53Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:53Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:53Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png
[2016-02-23T09:53:53Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:53Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:54Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-150x150.png
[2016-02-23T09:53:54Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:54Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:55Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-300x187.png
[2016-02-23T09:53:55Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:55Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:55Z] INFO: import_wordpress: Downloading http://davidak.de/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png => new_site/files/blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png
[2016-02-23T09:53:55Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): davidak.de
[2016-02-23T09:53:55Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): www.davidak.de
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "Google " because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "Startseite" because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "NO TITLE" because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "Blog" because it seems to contain no content.
[2016-02-23T09:53:55Z] WARNING: import_wordpress: Not going to import "Impressum" because it seems to contain no content.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugin_categories.py", line 124, in execute
    return self._execute(options, args)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 332, in _execute
    self.import_posts(channel)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 1015, in import_posts
    self.process_item_if_post_or_page(item)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 996, in process_item_if_post_or_page
    out_folder_slug = self.import_postpage_item(item, wordpress_namespace, 'posts', attachments)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/command/import_wordpress.py", line 938, in import_postpage_item
    rewrite_html)
  File "/usr/local/lib/python3.5/site-packages/nikola/plugins/basic_import.py", line 130, in write_content
    doc = html.document_fromstring(content)
  File "/usr/local/lib/python3.5/site-packages/lxml/html/__init__.py", line 755, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty
```

**Comment by felixfontein** [comment]
This is not a bug in the WordPress compiler and thus completely unrelated to the import mode, so we can merge this discussion with the one in #136.
