### ISSUE TITLE
Mustache TypeError

### ISSUE THREAD

**Issue by tritium21** [getnikola/plugins#139]
I am including the complete steps and output to reproduce.

```
(.venv)tritium@gesa:~/<redacted>$ mkdir temp
(.venv)tritium@gesa:~/<redacted>$ cd temp/
(.venv)tritium@gesa:~/<redacted>/temp$ nikola init -q .
[2016-02-27T05:27:15Z] INFO: init: Created empty site at ..
(.venv)tritium@gesa:~/<redacted>/temp$ nikola plugin -i mustache
[2016-02-27T05:27:29Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): plugins.getnikola.com
[2016-02-27T05:27:29Z] INFO: plugin: Downloading 'https://plugins.getnikola.com/v7/mustache.zip'
[2016-02-27T05:27:29Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): plugins.getnikola.com
[2016-02-27T05:27:29Z] INFO: plugin: Extracting: mustache into plugins/
(.venv)tritium@gesa:~/<redacted>/temp$ nikola new_post -t "Test post"
Creating New Post
-----------------

Title: Test post
Scanning posts......done!
[2016-02-27T05:27:49Z] INFO: new_post: Your post's text is at: posts/test-post.rst
(.venv)tritium@gesa:~/<redacted>/temp$ nikola build
Scanning posts......done!
.  render_tags:output/categories/index.html
.  render_galleries:output/galleries
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/js/jquery.colorbox-min.js
.  copy_assets:output/assets/js/flowr.plugin.js
.  copy_assets:output/assets/js/jquery.colorbox.js
.  copy_assets:output/assets/js/jquery.js
.  copy_assets:output/assets/js/jquery.min.js
.  copy_assets:output/assets/js/jquery.min.map
.  copy_assets:output/assets/js/bootstrap.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-tr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-et.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ru.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-bg.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-cs.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-pl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-hr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-lv.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-kr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fi.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-bn.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-uk.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-de.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fa.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-it.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ar.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-zh-TW.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-gl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-id.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sk.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-es.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ro.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-zh-CN.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-nl.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-fr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-hu.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-si.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-my.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-lt.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-gr.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ca.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-ja.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-no.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-pt-BR.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-sv.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-he.js
.  copy_assets:output/assets/js/colorbox-i18n/jquery.colorbox-da.js
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.ttf
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.eot
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff2
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.svg
.  copy_assets:output/assets/fonts/glyphicons-halflings-regular.woff
.  copy_assets:output/assets/css/bootstrap-theme.css.map
.  copy_assets:output/assets/css/bootstrap-theme.css
.  copy_assets:output/assets/css/colorbox.css
.  copy_assets:output/assets/css/docs.css
.  copy_assets:output/assets/css/bootstrap.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/bootstrap-theme.min.css.map
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/bootstrap.min.css.map
.  copy_assets:output/assets/css/bootstrap-theme.min.css
.  copy_assets:output/assets/css/bootstrap.css.map
.  copy_assets:output/assets/css/images/loading.gif
.  copy_assets:output/assets/css/images/controls.png
.  copy_assets:output/assets/css/images/ie6/borderTopLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomRight.png
.  copy_assets:output/assets/css/images/ie6/borderBottomCenter.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleRight.png
.  copy_assets:output/assets/css/images/ie6/borderMiddleLeft.png
.  copy_assets:output/assets/css/images/ie6/borderBottomLeft.png
.  copy_assets:output/assets/css/images/ie6/borderTopCenter.png
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/ipython.min.css.map
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/code.css
.  render_mustache:output/mustache-template.html
.  render_mustache:output/mustache.html
.  render_listings:output/listings/index.html
.  render_sources:output/posts/test-post.rst
.  render_archive:output/2016/index.html
.  render_archive:output/archive.html
.  render_posts:timeline_changes
.  render_posts:cache/posts/test-post.html
.  render_indexes:output/index.html
.  render_pages:output/posts/test-post.html
.  generate_rss:output/rss.xml
.  render_mustache:output/posts/test-post.json
########################################
TaskError - taskid:render_mustache:output/posts/test-post.json
PythonAction Error
Traceback (most recent call last):
  File "/home/tritium/<redacted>/.venv/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/tritium/<redacted>/temp/plugins/mustache/mustache/__init__.py", line 107, in write_file
    post.date.strftime(self.site.GLOBAL_CONTEXT['date_format']),
TypeError: strftime() argument 1 must be str, not TranslatableSetting



(.venv)tritium@gesa:~/<redacted>/temp$ nikola --version
Nikola vv7.7.6
```

**Comment by Kwpolska** [comment]
This was done incorrectly, and so it broke. I switched to `post.formatted_date`. Should work now.
