### ISSUE TITLE
Wiki plugin doesn't work with python 3

### ISSUE THREAD

**Issue by ralsina** [getnikola/plugins#151]
```
(nikola) ralsina@clakker:~/Desktop/proyectos/nikola/master/foo$ nikola plugin -i wiki
[2016-06-03T23:42:34Z] WARNING: Nikola: In order to USE_BUNDLES, you must install the "webassets" Python package.
[2016-06-03T23:42:34Z] WARNING: bundles: Setting USE_BUNDLES to False.
[2016-06-03T23:42:34Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): plugins.getnikola.com
[2016-06-03T23:42:35Z] INFO: plugin: Downloading 'https://plugins.getnikola.com/v7/wiki.zip'
[2016-06-03T23:42:35Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): plugins.getnikola.com
[2016-06-03T23:42:36Z] INFO: plugin: Extracting: wiki into plugins/
[2016-06-03T23:42:36Z] NOTICE: plugin: This plugin has Python dependencies.
[2016-06-03T23:42:36Z] INFO: plugin: Installing dependencies with pip...
Collecting creole (from -r plugins/wiki/requirements.txt (line 1))
  Downloading creole-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ki2ewukc/creole/setup.py", line 4, in <module>
        import creole
      File "/tmp/pip-build-ki2ewukc/creole/creole/__init__.py", line 28, in <module>
        from creole.rules import Rules
      File "/tmp/pip-build-ki2ewukc/creole/creole/rules.py", line 144
        self.wiki = ur'''(?P<wiki>[%s]\w+[%s]\w+)''' % (up_case, up_case)
                                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ki2ewukc/creole/
[2016-06-03T23:42:39Z] ERROR: plugin: Could not install the dependencies.
Contents of the requirements.txt file:

    creole

You have to install those yourself or through a package manager.

```

**Comment by Kwpolska** [comment]
That’s creole’s fault. Does anybody even *like* wiki markup?

**Comment by ralsina** [comment]
And the alternative nxcreole is py2 also. And we have the media wiki one
too. I will just add a note to the Readme.

**Comment by ralsina** [comment]
Closing. It is what it is.
