### ISSUE TITLE
[orgmode] plugin import error due to encoding

### ISSUE THREAD

**Issue by jamescasbon** [getnikola/plugins#161]
```
[2016-08-20T23:22:53Z] ERROR: yapsy: Unable to import plugin: /home/james/Src/blog/plugins/orgmode/orgmode
Traceback (most recent call last):
  File "/home/james/.local/lib/python3.5/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 763, in get_code
  File "/usr/lib/python3.5/imp.py", line 156, in get_data
    return file.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
Scanning posts....Cannot find 'orgmode' compiler; it might require an extra plugin -- do you have it installed?
```

The file contains the copyright symbol, removing the whole header makes it work.

**Comment by Kwpolska** [comment]
Fix your OS encoding to something with UTF-8 (check `locale -a` output; make sure your OS generates the necessary locales).

**Comment by icarito** [comment]
I'm pretty sure my OS is fine utf-8 wise but I get the same error.
```
[2016-09-29T06:56:57Z] WARNING: Nikola: The RSS_READ_MORE_LINK option is deprecated, use FEED_READ_MORE_LINK instead.
[2016-09-29T06:56:57Z] WARNING: Nikola: Could not guess locale for language es, using locale C
[2016-09-29T06:56:57Z] WARNING: Nikola: Please fix your OS locale configuration or use the LOCALES option in conf.py to specify your preferred locale.
[2016-09-29T06:56:57Z] WARNING: Nikola: Make sure to use an UTF-8 locale to ensure Unicode support.
[2016-09-29T06:56:57Z] WARNING: Nikola: A single list as DEPLOY_COMMANDS is deprecated.  DEPLOY_COMMANDS should be a dict, with deploy preset names as keys and lists of commands as values.
[2016-09-29T06:56:57Z] WARNING: Nikola: The key `default` is used by `nikola deploy`:
[2016-09-29T06:56:57Z] WARNING: Nikola: DEPLOY_COMMANDS = {'default': ["rsync -rav -e 'ssh -p 2244' output/ icarito@vivapython.com:/srv/vivapython.com/"]}
[2016-09-29T06:56:57Z] INFO: Nikola: (The above can be used with `nikola deploy` or `nikola deploy default`.  Multiple presets are accepted.)
[2016-09-29T06:56:57Z] WARNING: Nikola: WRITE_TAG_CLOUD is not set in your config.  Defaulting to True (== writing tag_cloud_data.json).
[2016-09-29T06:56:57Z] WARNING: Nikola: Please explicitly add the setting to your conf.py with the desired value, as the setting will default to False in the future.
[2016-09-29T06:56:57Z] ERROR: yapsy: Unable to import plugin: /home/icarito/Proyectos/vivapython/vivapython.com/plugins/book_figure/book_figure
Traceback (most recent call last):
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/imp.py", line 156, in get_data
    return file.read()
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
Scanning posts....done!
Traceback (most recent call last):
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/nikola.py", line 1795, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/nikola.py", line 1789, in flatten
    for t in task:
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/plugins/task/listings.py", line 178, in gen_tasks
    template_deps = self.site.template_system.template_deps('listing.tmpl')
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 129, in template_deps
    self.dependency_cache[template_name] = [filename] + self.get_deps(filename)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 123, in get_deps
    return self.get_string_deps(text)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 114, in get_string_deps
    sub_deps = self.get_deps(filename)
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/site-packages/nikola/plugins/template/jinja.py", line 122, in get_deps
    text = fd.read()
  File "/home/icarito/Proyectos/vivapython/vivapython.com/.direnv/python-3.5.2+/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2267: ordinal not in range(128)
```
Here's my locales:

```
$ locale
LANG=es_PE.utf8
LANGUAGE=es_PE:es
LC_CTYPE="es_PE.utf8"
LC_NUMERIC="es_PE.utf8"
LC_TIME="es_PE.utf8"
LC_COLLATE="es_PE.utf8"
LC_MONETARY="es_PE.utf8"
LC_MESSAGES="es_PE.utf8"
LC_PAPER="es_PE.utf8"
LC_NAME="es_PE.utf8"
LC_ADDRESS="es_PE.utf8"
LC_TELEPHONE="es_PE.utf8"
LC_MEASUREMENT="es_PE.utf8"
LC_IDENTIFICATION="es_PE.utf8"
LC_ALL=
$ locale -a
C
C.UTF-8
es_PE.utf8
POSIX
```

This is all under Python3.5 virtualenv.

**Comment by icarito** [comment]
By the way my site is built from https://github.com/somosazucar/vivapython

**Comment by Kwpolska** [comment]
Have you read the traceback? It refers to the `book_figure` plugin, not to `orgmode`. Python should use UTF-8 here, but it doesn’t. I forced it just in case.

But does your OS really have a `utf8` locale instead of `UTF-8`? Is that officially sanctioned by your OS?
