### ISSUE TITLE
Issue with org mode

### ISSUE THREAD

**Issue by olymk2** [getnikola/plugins#184]
I just installed nikola and enabled the org mode plugin but its not working.

```
nikola build
Scanning posts........done!
.  render_archive:output/2016/index.html
.  render_posts:timeline_changes
.  render_posts:cache/posts/fetch-jira-summary-from-jira-id-under-cursor-with-emacs.html
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Cannot fontify src block (htmlize.el >= 1.34 required)
Saving file /tmp/nik/do_blog/cache/posts/fetch-jira-summary-from-jira-id-under-cursor-with-emacs.html...
Wrote /tmp/nik/do_blog/cache/posts/fetch-jira-summary-from-jira-id-under-cursor-with-emacs.html
########################################
TaskError - taskid:render_posts:cache/posts/fetch-jira-summary-from-jira-id-under-cursor-with-emacs.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nikola/post.py", line 489, in compile
    self.is_two_file),
  File "/tmp/nik/do_blog/plugins/orgmode/orgmode.py", line 75, in compile_html
    post = self.site.post_per_input_file[source]
AttributeError: 'Nikola' object has no attribute 'post_per_input_file'
```

Any ideas on why, i created the file with nikola new_post and have no other files yet.

**Comment by Kwpolska** [comment]
You are probably running an ancient version of Nikola. Please upgrade.

**Comment by olymk2** [comment]
Okay i will try using from master, I am currently on 7.6.4 from an apt repository

**Comment by Kwpolska** [comment]
[Just install from pip in a virtualenv.](https://getnikola.com/getting-started.html) The Debian package is unsupported.

**Comment by olymk2** [comment]
yeah I have installed via pip, may use docker image or build my own if yours does not container org mode. 
that's for another day, thanks for the help :)

**Comment by Kwpolska** [comment]
Installing with pip in a virtualenv is the way we recommend the most for ease of use; using OS packages is also fine as long as they aren’t outdated by 14 months.
