### ISSUE TITLE
All of a sudden getting this error

### ISSUE THREAD

**Issue by zamansky** [getnikola/plugins#194]
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nikola/post.py", line 520, in compile
    self.is_two_file)
  File "/home/zamansky/gh/cestlaz.github.io/plugins/orgmode/orgmode.py", line 79, in compile_html
    with open(dest, 'r',encoding='utf-8' ) as inf:
TypeError: 'encoding' is an invalid keyword argument for this function

cache/posts/using-emacs-26-gcal.html

**Comment by zamansky** [comment]
Sorry - my bad -- mixed up python versions - verything works.

**Comment by Kwpolska** [comment]
There was a Python 2 compatibility bug, I fixed that.
