### ISSUE TITLE
[iarchiver]

### ISSUE THREAD

**Issue by drym3r** [getnikola/plugins#213]
Hi
When executing `nikola iarchiver` I get:
`Scanning posts..done!
[2017-02-03T09:47:34Z] INFO: iarchiver: Beginning submission of archive requests. This can take some time....
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/doit/doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "/usr/lib64/python3.6/site-packages/doit/cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "/usr/lib64/python3.6/site-packages/nikola/plugin_categories.py", line 130, in execute
    return self._execute(options, args)
  File "/home/drymer/Documentos/blog/plugins/iarchiver/iarchiver.py", line 86, in _execute
    postdate_sitetime = self.site.tzinfo.localize(postdate)
AttributeError: 'tzfile' object has no attribute 'localize'
`
Any idea?

**Comment by da2x** [comment]
Have you installed pytz? I should drop that dependency, but for now you can probably work around this by installing that.

**Comment by drym3r** [comment]
I didn't, but I just install it and it stills shows the same.
