### ISSUE TITLE
[sidebar] Build fails after installing sidebar plugin

### ISSUE THREAD

**Issue by KonstantinShemyak** [getnikola/plugins#233]
My site builds fine:

```
(nikola)$ nikola build
Scanning posts.....done!
```
I install `sidebar` plugin (do not change any files):

```
(nikola)$ nikola plugin -i sidebar
[2017-06-02T16:58:54Z] INFO: plugin: Downloading 'https://plugins.getnikola.com/v7/sidebar.zip'
[2017-06-02T16:58:54Z] INFO: plugin: Extracting: sidebar into plugins/
```
After which the build fails:
```
(nikola)$ nikola build
Scanning posts.....done!
Traceback (most recent call last):
  File "/home/user/nikola/lib/python3.5/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/user/nikola/lib/python3.5/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/user/nikola/lib/python3.5/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/user/nikola/lib/python3.5/site-packages/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/user/nikola/lib/python3.5/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/user/nikola/lib/python3.5/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/user/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1821, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/user/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1816, in flatten
    for ft in flatten(t):
  File "/home/user/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1815, in flatten
    for t in task:
  File "/home/user/nikola/my_new_site/plugins/sidebar/sidebar.py", line 134, in _prepare_sidebar
    for taxonomy in self.site.taxonomy_plugins.keys():
AttributeError: 'Nikola' object has no attribute 'taxonomy_plugins'
```
Version info:
```
(nikola)$ nikola --version
Nikola v7.8.1
```

**Comment by Kwpolska** [comment]
The sidebar plugin requires Nikola v7.8.2 or newer — run `pip install --upgrade Nikola`.

**Comment by KonstantinShemyak** [comment]
Thanks for the immediate response!
Version requirement at https://plugins.getnikola.com/v7/sidebar/ also can be updated.

**Comment by Kwpolska** [comment]
Where? It says *Supports Nikola v7.8.2 or newer*.

**Comment by KonstantinShemyak** [comment]
Whoops, sorry, page has not been reloaded. Case closed!
