### ISSUE TITLE
rest_html5: Broken with rst2html5 >= 1.9.2

### ISSUE THREAD

**Issue by pellenilsson** [getnikola/plugins#239]
Trying to use the plugin with latest version of rst2html5 fails to build:

    .  render_posts:cache/error_pages/404.html
    ########################################
    TaskError - taskid:render_posts:cache/error_pages/404.html
    PythonAction Error
    Traceback (most recent call last):
      File "/home/pelle/src-mine/pantarei/venv/lib/python3.5/site-packages/doit/action.py", line 383, in execute
        returned_value = self.py_callable(*self.args, **kwargs)
      File "/home/pelle/src-mine/pantarei/venv/lib/python3.5/site-packages/nikola/post.py", line 485, in compile
        self.is_two_file),
      File "/home/pelle/src-mine/pantarei/plugins/rest_html5/rest_html5.py", line 106, in compile_html
        }, logger=self.logger, source_path=source, l_add_ln=add_ln)
      File "/home/pelle/src-mine/pantarei/plugins/rest_html5/rest_html5.py", line 269, in rst2html
        writer = rst2html5.HTML5Writer()
    AttributeError: module 'rst2html5' has no attribute 'HTML5Writer'

**Comment by pellenilsson** [comment]
Seems to be caused by this upstream commit which renames the rst2html5 module in order to resolve a new conflict with `docuitls`:

https://bitbucket.org/andre_felipe_dias/rst2html5/commits/1d61740764541e5700f4aed6bbc2a6fee1c9b30e
