### ISSUE TITLE
[ical] crash after installation

### ISSUE THREAD

**Issue by felipem775** [getnikola/plugins#277]
Nikola v7.8.15, clean installation from pip
Python 3.6.4 
icalendar 4.0.1
os: linuxmint 18.3

After run `nikola plugin -i ical` nikola crash with any command:

```bash
$ nikola version    
Traceback (most recent call last):
  File "/home/user/workspace/nikola/env/bin/nikola", line 11, in <module>
    sys.exit(main())
  File "/home/user/workspace/nikola/env/lib/python3.6/site-packages/nikola/__main__.py", line 176, in main
    _ = DN.run(oargs)
  File "/home/user/workspace/nikola/env/lib/python3.6/site-packages/nikola/__main__.py", line 352, in run
    self.nikola.init_plugins()
  File "/home/user/workspace/nikola/env/lib/python3.6/site-packages/nikola/nikola.py", line 1195, in init_plugins
    self._activate_plugins_of_category("ShortcodePlugin")
  File "/home/user/workspace/nikola/env/lib/python3.6/site-packages/nikola/nikola.py", line 1341, in _activate_plugins_of_category
    plugin_info.plugin_object.set_site(self)
  File "/home/user/workspace/nikola/blog/plugins/ical/ical.py", line 36, in set_site
    super(CalendarPlugin, self).set_site(site)
  File "/home/user/workspace/nikola/env/lib/python3.6/site-packages/nikola/plugin_categories.py", line 413, in set_site
    site.register_shortcode(self.name, self.handler)
AttributeError: 'CalendarPlugin' object has no attribute 'handler'
```

**Comment by Kwpolska** [comment]
Should work now, please reinstall.
