### ISSUE TITLE
Support Tor-traffic!

### ISSUE THREAD

**Issue by GammaSQ** [getnikola/plugins#282]
Or rather, don't block Tor!
This command works as expected without Tor (tested on fedora with optional whonix-proxy inserted), but throws an error when using the Tor network:

    $ nikola plugin -l
    Traceback (most recent call last):
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
        return command.parse_execute(args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
        return self.execute(params, args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugin_categories.py", line 134, in execute
        return self._execute(options, args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 149, in _execute
        return self.list_available(url)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 161, in list_available
        data = self.get_json(url)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 354, in get_json
        self.json = requests.get(url).json()
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/requests/models.py", line 896, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ralsina** [comment]
This is not intentional, but not sure we can do much about it. In this
case, I suspect our CDN is blocking access to the content via Tor.
If you have git and can connect to github via tor+https, then you can just
get the themes from our repo at

https://github.com/getnikola/nikola-themes.git

**Comment by Kwpolska** [comment]
Feel free to complain to CloudFlare. Opening the website in a browser might let you complete a challenge, which will make your connection trusted.

**Comment by ralsina** [comment]
Actually, it looks like we **could** open up a little more for Tor incomings:

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-

**Comment by Kwpolska** [comment]
Whitelisting all of Tor certainly does not sound like a good idea.

**Comment by GammaSQ** [comment]
Thanks for the workaround, is there a similar way to install plugins?

@Kwpolska Would a more informative error message be possible? I pretty much found out by accident that Tor was the culprit.

**Comment by ralsina** [comment]
Sure. https://github.com/getnikola/plugins

In both cases just take the folder of the theme/plugin you want and copy it
in themes/plugins (and check its README)

**Comment by Kwpolska** [comment]
Reopening for more informative error messages.
