### ISSUE TITLE
NotImplementedError building my blog

### ISSUE THREAD

**Issue by asmeurer** [getnikola/plugins#289]
### Environment (if reporting a bug)

**Python Version:**

3.6

**Nikola Version:**

8.0.1

**Operating System:**
Happens on both Mac and Linux (Travis)

### Description:

See https://travis-ci.org/asmeurer/blog/builds/452092591. The sources are at https://github.com/asmeurer/blog.

I get 

```pytb
.  render_posts:cache/posts/automatically-deploying-this-blog-to-github-pages-with-travis-ci.html
TaskError - taskid:render_posts:cache/posts/automatically-deploying-this-blog-to-github-pages-with-travis-ci.html
PythonAction Error
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/post.py", line 652, in compile
    lang)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nikola/plugin_categories.py", line 323, in compile
    raise NotImplementedError()
```

This same blog built just fine with an older version of Nikola (see the Travis history).

**Comment by asmeurer** [comment]
Great. It works now.
