### ISSUE TITLE
[orgmode] bad org configuration

### ISSUE THREAD

**Issue by peng051410** [getnikola/plugins#307]
when i run nikola github_deploy, i got this error
`
zsh:1: unknown file attribute: i
TaskError - taskid:render_posts:cache/posts/apollo-config-swim.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/tomyli/github/blog/plugins/orgmode/orgmode.py", line 74, in compile
    subprocess.check_call(command)
  File "/Users/tomyli/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['emacs', '--batch', '-l', '/Users/tomyli/github/blog/plugins/orgmode/init.el', '--eval', '(nikola-html-export "/Users/tomyli/github/blog/posts/apollo-config-swim
.org" "/Users/tomyli/github/blog/cache/posts/apollo-config-swim.html")']' returned non-zero exit status 1.                                                                                               

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomyli/nikola/lib/python3.6/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/tomyli/nikola/lib/python3.6/site-packages/nikola/post.py", line 652, in compile
    lang)
  File "/Users/tomyli/github/blog/plugins/orgmode/orgmode.py", line 93, in compile
    raise Exception('Cannot compile {0} -- bad org-mode configuration (return code {1})'.format(source, e.returncode))
Exception: Cannot compile posts/apollo-config-swim.org -- bad org-mode configuration (return code 1)
`
What should i do?

**Comment by LEXUGE** [comment]
Have you solved it?

**Comment by peng051410** [comment]
> Have you solved it?

Sorry, I use hugo now!
