### ISSUE TITLE
[subindexes] pagekind is Undefined

### ISSUE THREAD

**Issue by sebastianstigler** [getnikola/plugins#315]
I'm using Nikola V8.0.2 and want to use the subindexes plugin. But when I build my site I get an traceback.

Here a repo for this error:

    nikola init -d

I set the destination to `subindextest` and hit on all other questions enter. Then I installed the plugin and build the site:

    nikola plugin -i subindexes
    nikola build

This is the output I get:

```
Scanning posts........done!
.  render_posts:timeline_changes
.  render_posts:cache/pages/dr-nikolas-vendetta.html
[2019-10-09T08:00:57Z] WARNING: Nikola: In order to use the typogrify filter, you must install the "typogrify" Python package.
.  render_posts:cache/pages/path_handlers.html
.  render_posts:cache/pages/creating-a-theme.html
.  render_posts:cache/pages/charts.html
[2019-10-09T08:00:57Z] WARNING: Nikola: In order to use the Chart directive, you must install the "pygal" Python package.
.  render_posts:cache/pages/social_buttons.html
.  render_posts:cache/pages/listings-demo.html
.  render_posts:cache/pages/1.html
.  render_posts:cache/pages/bootstrap-demo.html
.  render_posts:cache/pages/extending.html
.  render_posts:cache/pages/internals.html
.  render_posts:cache/pages/manual.html
.  render_posts:cache/pages/quickref.html
.  render_posts:cache/pages/quickstart.html
.  render_posts:cache/posts/1.html
.  render_posts:cache/pages/theming.html
.  render_listings:output/listings/index.html
.  render_listings:output/listings/hello.py.html
.  render_listings:output/listings/hello.py
.  render_listings:output/listings/__pycache__/index.html
.  render_galleries:output/galleries
.  render_galleries:output/galleries/demo
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_galleries:output/galleries/demo/tesla_lightning1_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_lightning1_lg.jpg
.  render_galleries:output/galleries/demo/tesla4_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla4_lg.jpg
.  render_galleries:output/galleries/demo/tesla_lightning2_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_lightning2_lg.jpg
.  render_galleries:output/galleries/demo/tesla_tower1_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_tower1_lg.jpg
.  render_galleries:output/galleries/demo/tesla_conducts_lg.thumbnail.jpg
.  render_galleries:output/galleries/demo/tesla_conducts_lg.jpg
.  render_galleries:cache/galleries/demo/index.html
.  render_galleries:output/galleries/demo/index.html
.  render_galleries:output/galleries/demo/rss.xml
.  copy_assets:output/assets/css/bootblog.css
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/js/jquery.min.js
.  copy_assets:output/assets/js/popper.min.js
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/js/gallery.min.js
.  copy_assets:output/assets/js/fancydates.min.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/gallery.js
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/css/code.css
.  render_subindexes:output/posts/index.html
TaskError - taskid:render_subindexes:output/posts/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/nikola/nikola.py", line 1370, in render_template
    template_name, None, local_context)
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/nikola/plugins/template/mako.py", line 113, in render_template
    data = template.render_unicode(**context)
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/mako/template.py", line 482, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/sebastian/.virtualenvs/nikola_p3/lib/python3.5/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/sebastian/tmp/nikola/subindextest/cache/.mako.tmp/base.tmpl.py", line 120, in render_body
    context['self'].before_content(**pageargs)
  File "/home/sebastian/tmp/nikola/subindextest/cache/.mako.tmp/index.tmpl.py", line 250, in render_before_content
    if 'main_index' in pagekind and is_frontmost_index and featured and (theme_config.get('featured_large') or theme_config.get('featured_small')):
TypeError: argument of type 'Undefined' is not iterable

########################################
render_subindexes:output/posts/index.html <stdout>:

```

**Comment by Kwpolska** [comment]
Fixed, please reinstall the plugin.
