### ISSUE TITLE
Webapp: 500 Internal Server Error

### ISSUE THREAD

**Issue by Elinvention** [getnikola/plugins#77]
```
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/elia/nikola/plugins/webapp/webapp.py", line 98, in edit
    return render('edit_post.tpl', context)
  File "/home/elia/nikola/plugins/webapp/webapp.py", line 176, in render
    return lookup.get_template(template_name).render_unicode(**context)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "base_tpl", line 30, in render_body
  File "edit_post_tpl", line 67, in render_content
AttributeError: 'NoneType' object has no attribute 'items'
```
This is what happens when I try to edit a post or a page.

**Comment by ralsina** [comment]
I can't reproduce it. I did find a bug where it crashes with a unicode error, which I am about to merge.

**Comment by Kwpolska** [comment]
Wait, why is this still a thing?  [Coil](/getnikola/coil) is a better solution.

**Comment by ralsina** [comment]
And this is 100x easier to start using, isn't it?

**Comment by Kwpolska** [comment]
We could try dropping the extra dependencies from Coil.  Should not be that hard to do with a little refactoring…
