### ISSUE TITLE
Something went wrong with metadata update

### ISSUE THREAD

**Issue by ralsina** [getnikola/plugins#84]
```
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/doit-0.28.0-py2.7.egg/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/ralsina/.virtualenvs/nikola/local/lib/python2.7/site-packages/doit-0.28.0-py2.7.egg/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/ralsina/Desktop/proyectos/nikola/master/nikola/plugin_categories.py", line 114, in execute
    self._execute(options, args)
  File "/home/ralsina/Desktop/proyectos/static/plugins/upgrade_metadata/upgrade_metadata.py", line 80, in _execute
    with io.open(fname, 'r', encoding='utf-8') as fh:
IOError: [Errno 2] No existe el archivo o el directorio: 'posts/new-nikola-feature-wordpresscom-importer.txt.meta'
```
The files that actually exist:

```
(nikola)ralsina@yoga:~/Desktop/proyectos/static$ ls posts/new-nikola-feature-wordpresscom-importer.* -1
posts/new-nikola-feature-wordpresscom-importer.meta
posts/new-nikola-feature-wordpresscom-importer.meta.es
posts/new-nikola-feature-wordpresscom-importer.txt
posts/new-nikola-feature-wordpresscom-importer.txt.es
```

**Comment by Kwpolska** [comment]
fixed in 2a5db98bd1d48ba625a5dc66833c12086b8c412d
