### ISSUE TITLE
odt plugin raises an exception

### ISSUE THREAD

**Issue by humitos** [getnikola/plugins#96]
I tried odt plugin with Nikola 7.6.2 and a empty init site: https://plugins.getnikola.com/#odt

```
$ nikola build
Scanning posts...Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/__main__.py", line 282, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/doit/loader.py", line 296, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/nikola.py", line 1386, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/nikola.py", line 1380, in flatten
    for t in task:
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/plugins/task/indexes.py", line 51, in gen_tasks
    self.site.scan_posts()
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/nikola.py", line 1484, in scan_posts
    timeline = p.plugin_object.scan()
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/plugins/misc/scan_posts.py", line 98, in scan
    self.site.get_compiler(base_path)
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/post.py", line 143, in __init__
    default_metadata, self.newstylemeta = get_meta(self, self.config['FILE_METADATA_REGEXP'], self.config['UNSLUGIFY_TITLES'])
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/post.py", line 995, in get_meta
    meta.update(get_metadata_from_file(post.source_path, config, lang))
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/nikola/post.py", line 848, in get_metadata_from_file
    raise ValueError('Error reading {0}: Nikola only supports UTF-8 files'.format(source_path))
ValueError: Error reading posts/my_post.odt: Nikola only supports UTF-8 files
```

**Comment by Kwpolska** [comment]
I think you need 2-file metadata for this to work.
