### ISSUE TITLE
wordpress_compiler fails on 7.6.2

### ISSUE THREAD

**Issue by humitos** [getnikola/plugins#97]
```
$ nikola build
[2015-08-02T22:31:47Z] ERROR: yapsy: Unable to create plugin object: /tmp/wordpress-blog/plugins/wordpress_compiler/wordpress
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/home/humitos/.virtualenvs/tmp-d115798aa0247311/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 531, in instanciateElement
    return element()
  File "/tmp/wordpress-blog/plugins/wordpress_compiler/wordpress/wordpress.py", line 117, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
Scanning posts.....Cannot find 'wordpress' compiler; it might require an extra plugin -- do you have it installed?
$
```

@felixfontein do you know what is happening here?

**Comment by Kwpolska** [comment]
That’s Python 3.x syntax, `super()` is a bit more complicated in Python 2.

**Comment by Kwpolska** [comment]
Fixed (didn’t test though).

**Comment by felixfontein** [comment]
Thanks for looking at it and fixing it. I'm currently away with an almost non-existent internet connection...
